
##Delete all table
#DROP TABLE T_USER;
/*DELETE FROM T_SHPEE_CONFIG;
DELETE FROM T_SHPEE_USER;
DELETE FROM T_USER_GROUP;
DELETE FROM T_ROLE;
DELETE FROM T_GROUP_ROLE;*/

CREATE TABLE IF NOT EXISTS T_SHPEE_CONFIG(
    SHPEE_KEY   char(32)    PRIMARY KEY NOT NULL,
    SHPEE_VALUE    char(32)    NOT NULL
);

CREATE TABLE IF NOT EXISTS T_SHPEE_USER(
    USER_ID     char(64)    PRIMARY KEY NOT NULL,
    USERNAME    varchar(64) UNIQUE NOT NULL,
    PASSWORD    char(64)    NOT NULL ,
    USER_GROUP  int NOT NULL,
    EMAIL       char(64)    UNIQUE,
    ENABLED     boolean DEFAULT TRUE,
    ACCOUNT_NON_EXPIRED boolean DEFAULT TRUE,
    CREDENTIALS_NON_EXPIRED boolean DEFAULT TRUE,
    ACCOUNT_NON_LOCKED  boolean DEFAULT TRUE
    );

CREATE TABLE IF NOT EXISTS T_USER_GROUP(
    GROUP_ID    int    PRIMARY KEY NOT NULL,
    GROUP_NAME    varchar(64) UNIQUE NOT NULL,
    ENABLED      boolean  DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS T_ROLE(
    ROLE_ID    int PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ROLE_NAME   char(32) NOT NULL,
    ENABLED      boolean  DEFAULT TRUE
)AUTO_INCREMENT=100000;

CREATE TABLE IF NOT EXISTS T_GROUP_ROLE(
    GROUP_ID    int NOT NULL,
    ROLE_ID   int NOT NULL
);