
spring:
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 1GB
      enabled: true
      max-request-size: 10GB

  datasource:
    username: root
    password: 654321^dcba
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mwork_dev?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    type: com.zaxxer.hikari.HikariDataSource
    schema: classpath:config/create.sql
    initialization-mode: always
mybatis:
  mapper-locations: classpath:config/*_mapper.xml
  type-aliases-package: com.xentn.shpee.mapper
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
