server:
  port: 8080
spring:
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 5MB
  datasource:
    username: root
    password: 654321^dcba
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shpee?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    type: com.mchange.v2.c3p0.ComboPooledDataSource
mybatis:
  mapper-locations: classpath:conf/mapper.xml
  type-aliases-package: top.yukino.config.Mapper
