server:
  port: 8080
#  address: 127.0.0.1
#  servlet:
 #   context-path: ~\shpee
#  address: ::1
spring:
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 50MB
      enabled: true
      max-request-size: 100MB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/shpee
    username: root
    password: 654321^dcba
    type: com.zaxxer.hikari.HikariDataSource

#   Mysql configure
#  datasource:
#    username: root
#    password: 654321^dcba
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/shpee?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
#    type: com.mchange.v2.c3p0.ComboPooledDataSource


#H2 configure
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:./shpeedb
#    schema:
#    - classpath:conf/table.sql
#    data:
#    - classpath:conf/insert.sql
#    username: sa
#    password: sa
#  h2:
#    console:
#      enabled: true

mybatis:
  mapper-locations: classpath:conf/mapper.xml
  type-aliases-package: top.yukino.config.Mapper
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true